let MENU =  [
  // --- Cà phê ---
  { id: 1, name: "Cà phê máy đen nóng", price: 15000, cat: "Cà phê" },
  { id: 2, name: "Cà phê máy sữa nóng", price: 15000, cat: "Cà phê" },
  { id: 3, name: "Cà phê đen đá máy", price: 15000, cat: "Cà phê" },
  { id: 4, name: "Cà phê sữa đá máy", price: 15000, cat: "Cà phê" },
  { id: 5, name: "Cà phê pha phin đen nóng", price: 15000, cat: "Cà phê" },
  { id: 6, name: "Cà phê phin sữa nóng", price: 15000, cat: "Cà phê" },
  { id: 7, name: "Cà phê phin đen đá", price: 15000, cat: "Cà phê" },
  { id: 8, name: "Cà phê phin sữa đá", price: 15000, cat: "Cà phê" },
  { id: 9, name: "Cà phê Sài Gòn", price: 18000, cat: "Cà phê" },
  { id: 10, name: "Cà phê kem muối", price: 20000, cat: "Cà phê" },
  { id: 11, name: "Cà phê kem trứng", price: 20000, cat: "Cà phê" },
  { id: 12, name: "Cà phê cốt dừa", price: 20000, cat: "Cà phê" },
  { id: 13, name: "Bạc xỉu đá", price: 20000, cat: "Cà phê" },
  { id: 14, name: "Ca cao đá", price: 20000, cat: "Cà phê" },
  // --- Trà Nóng ---
  { id: 15, name: "Trà gừng", price: 15000, cat: "Trà nóng" },
  { id: 16, name: "Trà cam quế", price: 15000, cat: "Trà nóng" },
  { id: 17, name: "Cacao nóng", price: 20000, cat: "Trà nóng" },
  { id: 18, name: "Cacao chuối", price: 20000, cat: "Trà nóng" },
  { id: 19, name: "Bạc xỉu nóng", price: 20000, cat: "Trà nóng" },
  { id: 20, name: "Trà lipton ngũ sắc", price: 20000, cat: "Trà nóng" },
  { id: 21, name: "Trà đào cam quế", price: 20000, cat: "Trà nóng" },
  { id: 22, name: "Trà cúc long nhãn", price: 20000, cat: "Trà nóng" },
  { id: 23, name: "Trà la hán sen vàng", price: 20000, cat: "Trà nóng" },
  { id: 24, name: "Trà chanh gừng ô mai", price: 20000, cat: "Trà nóng" },
  { id: 25, name: "Trà atiso", price: 20000, cat: "Trà nóng" },
  { id: 26, name: "Trà thảo mộc", price: 25000, cat: "Trà nóng" },
  { id: 27, name: "Matcha latte", price: 25000, cat: "Trà nóng" },
  // --- Trà ---
  { id: 28, name: "Trà sữa truyền thống (Size M)", price: 15000, cat: "Trà" },
  { id: 29, name: "Trà sữa truyền thống (Size L)", price: 20000, cat: "Trà" },
  { id: 30, name: "Trà sữa matcha (Size M)", price: 20000, cat: "Trà" },
  { id: 31, name: "Trà sữa matcha (Size L)", price: 25000, cat: "Trà" },
  { id: 32, name: "Trà sữa socola (Size M)", price: 20000, cat: "Trà" },
  { id: 33, name: "Trà sữa socola (Size L)", price: 25000, cat: "Trà" },
  { id: 34, name: "Trà sữa khoai môn (Size M)", price: 20000, cat: "Trà" },
  { id: 35, name: "Trà sữa khoai môn (Size L)", price: 25000, cat: "Trà" },
  { id: 36, name: "Trà đào (Size M)", price: 15000, cat: "Trà" },
  { id: 37, name: "Trà đào (Size L)", price: 20000, cat: "Trà" },
  { id: 38, name: "Trà đào cam xả (Size M)", price: 20000, cat: "Trà" },
  { id: 39, name: "Trà đào cam xả (Size L)", price: 25000, cat: "Trà" },
  { id: 40, name: "Trà vải (Size M)", price: 15000, cat: "Trà" },
  { id: 41, name: "Trà vải (Size L)", price: 20000, cat: "Trà" },
  { id: 42, name: "Trà tắc (Size M)", price: 15000, cat: "Trà" },
  { id: 43, name: "Trà tắc (Size L)", price: 20000, cat: "Trà" },
  { id: 44, name: "Trà chanh (Size M)", price: 15000, cat: "Trà" },
  { id: 45, name: "Trà chanh (Size L)", price: 20000, cat: "Trà" },
  { id: 46, name: "Trà bưởi hồng (Size M)", price: 20000, cat: "Trà" },
  { id: 47, name: "Trà bưởi hồng (Size L)", price: 25000, cat: "Trà" },
  { id: 48, name: "Trà sen vàng kem (Size L)", price: 25000, cat: "Trà" },
  { id: 49, name: "Trà chanh bạc hà (Size M)", price: 20000, cat: "Trà" },
  { id: 50, name: "Trà chanh bạc hà (Size L)", price: 25000, cat: "Trà" },
  { id: 51, name: "Trà xoài thạch dừa (Size M)", price: 20000, cat: "Trà" },
  { id: 52, name: "Trà xoài thạch dừa (Size L)", price: 25000, cat: "Trà" },
  { id: 53, name: "Trà dâu (Size M)", price: 20000, cat: "Trà" },
  { id: 54, name: "Trà dâu (Size L)", price: 25000, cat: "Trà" },
  { id: 55, name: "Trà ổi hồng chanh dây (Size M)", price: 20000, cat: "Trà" },
  { id: 56, name: "Trà ổi hồng chanh dây (Size L)", price: 25000, cat: "Trà" },
  { id: 57, name: "Trà nhãn hoa hồng (Size M)", price: 20000, cat: "Trà" },
  { id: 58, name: "Trà nhãn hoa hồng (Size L)", price: 25000, cat: "Trà" },
  { id: 59, name: "Trà ổi dâu (Size M)", price: 20000, cat: "Trà" },
  { id: 60, name: "Trà ổi dâu (Size L)", price: 25000, cat: "Trà" },
  { id: 61, name: "Trà xoài xanh xí muội (Size M)", price: 25000, cat: "Trà" },
  { id: 62, name: "Trà xoài xanh xí muội (Size L)", price: 28000, cat: "Trà" },
  { id: 63, name: "Trà lài đắc thơm (Size M)", price: 25000, cat: "Trà" },
  { id: 64, name: "Trà lài đắc thơm (Size L)", price: 28000, cat: "Trà" },
  { id: 65, name: "Trà cam hoa hồng (Size M)", price: 25000, cat: "Trà" },
  { id: 66, name: "Trà cam hoa hồng (Size L)", price: 28000, cat: "Trà" },
  { id: 67, name: "Trà trái cây mật ong (Size M)", price: 25000, cat: "Trà" },
  { id: 68, name: "Trà trái cây mật ong (Size L)", price: 28000, cat: "Trà" },
  { id: 69, name: "Trà trái cây (Size M)", price: 25000, cat: "Trà" },
  { id: 70, name: "Trà trái cây (Size L)", price: 28000, cat: "Trà" },
  { id: 71, name: "Trà bưởi hồng yakul (Size L)", price: 28000, cat: "Trà" },
  { id: 72, name: "Trà dâu yakul (Size L)", price: 28000, cat: "Trà" },
  { id: 73, name: "Trà la hán sương sáo (Size M)", price: 25000, cat: "Trà" },
  { id: 74, name: "Trà la hán sương sáo (Size L)", price: 28000, cat: "Trà" },
  // --- Matcha---
  { id: 75, name: "Matcha sữa xoài (Size M)", price: 25000, cat: "Matcha" },
{ id: 76, name: "Matcha sữa xoài (Size L)", price: 28000, cat: "Matcha" },
{ id: 77, name: "Matcha latte (Size M)", price: 25000, cat: "Matcha" },
{ id: 78, name: "Matcha latte (Size L)", price: 28000, cat: "Matcha" },
{ id: 79, name: "Matcha sữa dừa (Size M)", price: 25000, cat: "Matcha" },
{ id: 80, name: "Matcha sữa dừa (Size L)", price: 28000, cat: "Matcha" },
{ id: 81, name: "Matcha khoai môn (Size M)", price: 25000, cat: "Matcha" },
{ id: 82, name: "Matcha khoai môn (Size L)", price: 28000, cat: "Matcha" },
{ id: 83, name: "Matcha sữa hạt (Size M)", price: 25000, cat: "Matcha" },
{ id: 84, name: "Matcha sữa hạt (Size L)", price: 28000, cat: "Matcha" },
  // --- sữa chua ---
{ id: 85, name: "Sữa chua thuần khiết", price: 20000, cat: "Sữa chua" },
{ id: 86, name: "Sữa chua ổi", price: 25000, cat: "Sữa chua" },
{ id: 87, name: "Sữa chua việt quất", price: 25000, cat: "Sữa chua" },
{ id: 88, name: "Sữa chua nho", price: 25000, cat: "Sữa chua" },
{ id: 89, name: "Sữa chua dâu", price: 25000, cat: "Sữa chua" },
{ id: 90, name: "Sữa chua kiwi", price: 25000, cat: "Sữa chua" },
{ id: 91, name: "Sữa chua xoài", price: 25000, cat: "Sữa chua" },
{ id: 92, name: "Sữa chua chanh dây", price: 25000, cat: "Sữa chua" },
{ id: 93, name: "Sữa chua hạt đác", price: 25000, cat: "Sữa chua" },
{ id: 94, name: "Sữa chua yến mạch trái cây", price: 30000, cat: "Sữa chua" },
  // --- Nước ép---
{ id: 95, name: "Nước ép cà rốt", price: 25000, cat: "Nước ép" },
{ id: 96, name: "Nước ép cam", price: 25000, cat: "Nước ép" },
{ id: 97, name: "Nước ép dứa", price: 25000, cat: "Nước ép" },
{ id: 98, name: "Nước ép táo", price: 25000, cat: "Nước ép" },
{ id: 99, name: "Nước ép ổi", price: 25000, cat: "Nước ép" },
{ id: 100, name: "Nước ép cam + cà rốt", price: 25000, cat: "Nước ép" },
{ id: 101, name: "Nước ép cam + dứa", price: 25000, cat: "Nước ép" },
{ id: 102, name: "Nước ép cà rốt + dứa", price: 25000, cat: "Nước ép" },
  // --- Rau Má ---
  { id: 103, name: "Rau má cốt dừa (Size M)", price: 15000, cat: "Rau má" },
{ id: 104, name: "Rau má cốt dừa (Size L)", price: 20000, cat: "Rau má" },
{ id: 105, name: "Rau má đậu xanh (Size M)", price: 15000, cat: "Rau má" },
{ id: 106, name: "Rau má đậu xanh (Size L)", price: 20000, cat: "Rau má" },
{ id: 107, name: "Đậu xanh sữa dừa (Size M)", price: 20000, cat: "Rau má" },
{ id: 108, name: "Đậu xanh sữa dừa (Size L)", price: 25000, cat: "Rau má" },
 // --- Sinh Tố ---
{ id: 109, name: "Sinh tố dừa", price: 25000, cat: "Sinh tố" },
{ id: 110, name: "Sinh tố dâu", price: 25000, cat: "Sinh tố" },
{ id: 111, name: "Sinh tố nho", price: 25000, cat: "Sinh tố" },
{ id: 112, name: "Sinh tố kiwi", price: 25000, cat: "Sinh tố" },
{ id: 113, name: "Sinh tố việt quất", price: 25000, cat: "Sinh tố" },
{ id: 114, name: "Sinh tố xoài", price: 25000, cat: "Sinh tố" },
{ id: 115, name: "Sinh tố ổi", price: 25000, cat: "Sinh tố" },
{ id: 116, name: "Sinh tố Sampo / bơ (theo mùa)", price: 25000, cat: "Sinh tố" },
  // ---Đá xay --- 
{ id: 117, name: "Đá xay Socola", price: 25000, cat: "Đá xay" },
{ id: 118, name: "Đá xay Matcha", price: 25000, cat: "Đá xay" },
{ id: 119, name: "Đá xay Khoai môn", price: 25000, cat: "Đá xay" },
  // ---Giải khát --- 
{ id: 120, name: "Bò húc", price: 18000, cat: "Giải khát" },
{ id: 121, name: "Nước các loại", price: 15000, cat: "Giải khát" },
{ id: 122, name: "Cóc tai (Size M)", price: 15000, cat: "Giải khát" },
{ id: 123, name: "Cóc tai (Size L)", price: 20000, cat: "Giải khát" },
{ id: 124, name: "Chanh đá", price: 15000, cat: "Giải khát" },
{ id: 125, name: "Chanh muối", price: 15000, cat: "Giải khát" },
{ id: 126, name: "Soda Blue", price: 25000, cat: "Giải khát" },
// Ăn vặt
{ id: 127, name: "Bánh tráng ruốc nhỏ", price: 17000, cat: "Ăn vặt" },
{ id: 128, name: "Bánh tráng ruốc lớn", price: 30000, cat: "Ăn vặt" },
{ id: 129, name: "Tráng vỏ", price: 10000, cat: "Ăn vặt" },
{ id: 130, name: "Tráng chấm", price: 15000, cat: "Ăn vặt" },
  // Thuốc lá
{ id: 131, name: "Mèo lớn", price: 26000, cat: "Thuốc lá" },
{ id: 132, name: "Mèo nhỏ", price: 17000, cat: "Thuốc lá" },
{ id: 133, name: "Sài Gòn", price: 16000, cat: "Thuốc lá" },
{ id: 134, name: "Batto", price: 12000, cat: "Thuốc lá" }
  
];